"""empty message

Revision ID: bbe1aa1ae338
Revises: 
Create Date: 2021-05-05 17:31:27.636987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe1aa1ae338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=40), nullable=False),
    sa.Column('userPassword', sa.String(length=100), nullable=False),
    sa.Column('registerTime', sa.DateTime(), nullable=True),
    sa.Column('temporaryAddress', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporaryAddress'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('flowerpots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isAuto', sa.Boolean(), nullable=False),
    sa.Column('flowerpotName', sa.String(length=20), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('IP', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flowerpotName')
    )
    op.create_table('flowerpots_behaviors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setLED', sa.Float(), nullable=False),
    sa.Column('setWater', sa.Float(), nullable=False),
    sa.Column('isAuto', sa.Boolean(), nullable=False),
    sa.Column('controlTime', sa.DateTime(), nullable=False),
    sa.Column('FlowerpotId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FlowerpotId'], ['flowerpots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flowerpots_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('soilHumidity', sa.Float(), nullable=False),
    sa.Column('lightIntensity', sa.Float(), nullable=False),
    sa.Column('testTime', sa.DateTime(), nullable=False),
    sa.Column('FlowerpotId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FlowerpotId'], ['flowerpots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flowerpots_data')
    op.drop_table('flowerpots_behaviors')
    op.drop_table('flowerpots')
    op.drop_table('users')
    # ### end Alembic commands ###
